### ISSUE TITLE
Subgraph doesn't work for some ERC721 contracts

### ISSUE THREAD

**Issue by iammxt** [Amxx/subgraphs#3]
I was trying to [query the EIP721 subgraph on The Graph playground](https://thegraph.com/legacy-explorer/subgraph/amxx/eip721-subgraph?selected=playground) for all the NFTs managed by a contract, such as [0x06012c8cf97BEaD5deAe237070F9587f8E7A266d](https://etherscan.io/address/0x06012c8cf97bead5deae237070f9587f8e7a266d). I did some googling and following [this comment](https://github.com/OpenZeppelin/openzeppelin-contracts/issues/1102#issuecomment-819055217), I came up with this query:

```
{
  tokenRegistry(id: "0x06012c8cf97BEaD5deAe237070F9587f8E7A266d") {
    tokens {
      identifier
      owner {
        id
      }
    }
  }
}
```

However I got a `null` result:
```
{
  "data": {
    "tokenRegistry": null
  }
}
```

The same query with some different contract address such as [this](0x24d0cbd0d5d7b50212251c5dc7cb810e7af71f6a) works. So I was wondering whether there was some contract allowlist somewhere, but the closest I could find in the code base was this https://github.com/Amxx/subgraphs/blob/master/subgraphs/common/config/eip721.json, which doesn't look to me like it's filtering out any contract address.

@Amxx could you please advise if I am missing something from the query? Also, is this subgraph supposed to work for all ERC721 contracts on Ethereum or whether there's an allowlist somewhere? Thank you.

**Comment by Amxx** [comment]
Hello

This subgraph does index ALL ERC721 that have at least one token. It seems that you are querying a checksummed address. Subgraph IDs are lowercase only hex strings. Try running the same query with a lowercase address.

**Comment by Amxx** [comment]
I just noted you are looking for CryptoKitties. The crypto kitty registry is NOT an ERC721, and is therefore not indexed by this subgraph.

You'll find it indexed in https://thegraph.com/legacy-explorer/subgraph/amxx/non-standard-nfts, which might me slightly different (I've not updated it in a long time)

**Comment by iammxt** [comment]
Thanks for the quick answers! So the EIP721 subgraph does indexes all ERC721 tokens. I'd assume the same about the [EIP 1155 subgraph](https://thegraph.com/legacy-explorer/subgraph/amxx/eip1155-subgraph). Also, thanks for pointing out the subgraph to use for non-standard NFTs.
